function fkine = fkine(rob,in2)
%FKINE
%    FKINE = FKINE(ROB,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    23-Apr-2017 12:21:29

q1 = in2(:,1);
q2 = in2(:,2);
q3 = in2(:,3);
t2 = q1+q2+q3;
t3 = cos(t2);
t4 = sin(t2);
t5 = q1+q2;
fkine = reshape([t3,t4,0.0,0.0,-t4,t3,0.0,0.0,0.0,0.0,1.0,0.0,t3+cos(q1)+cos(t5),t4+sin(q1)+sin(t5),0.0,1.0],[4,4]);
